import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "@/styles/globals.css";

const urbanist = Urbanist({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-urbanist',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={urbanist.variable}>
      <body className={`${urbanist.className} text-foreground antialiased !font-default overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}